image: Visual Studio 2019

init:
  - git config --global core.autocrlf true

environment:
  matrix:
  - solution: InverseIndex/InverseIndex.sln

before_build:
  - nuget restore %solution%

build_script:
  project: $(solution)

test:
  - dotnet test %solution%
